"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$character"""

add_newline = false

[directory]
style = "bold green"

[git_branch]
format = '[\($branch\)]($style)'
style = "bold red"

[git_status]
style = "bold blue"
conflicted = "="
untracked = "?"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
stashed = "$"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bold bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "italic bold yellow"
