#!/bin/bash

source "$CONFIG_DIR/colors.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

# Bar Appearance
sketchybar --bar position=top \
                 height=40 \
                 blur_radius=30 \
                 y_offset=10 \
                 margin=10 \
                 padding_left=2 \
                 padding_right=2 \
                 corner_radius=10 \
                 color=$BAR_COLOR \
                 shadow=on \

# Changing Defaults 
default=(
  padding_left=5
  padding_right=5
  icon.font="SF Pro:Semibold:15.0"
  icon.color=$WHITE
  icon.padding_left=4
  icon.padding_right=4
  label.font="SF Pro:Semibold:15.0"
  label.color=$WHITE
  label.padding_left=4
  label.padding_right=4
  background.height=25
  background.corner_radius=6
  background.color=$BACKGROUND_2
)
sketchybar --default "${default[@]}"

# Left items
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# Right Items
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh

# Force all scripts to run the first time (never do this in a script)
sketchybar --update
